# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://dinhyen.github.io
title: Yen's Blog
subtitle: "Lens, Wheels, Skates, Keyboard"
author: Yen Tran
simple_search: http://google.com/search
description:

# Default date format is "ordinal" (resulting in "July 22nd 2007")
# You can customize the format as defined in
# http://www.ruby-doc.org/core-1.9.2/Time.html#method-i-strftime
# Additionally, %o will give you the ordinal representation of the day
date_format: "ordinal"

# RSS / Email (optional) subscription links (change if using something like Feedburner)
subscribe_rss: /atom.xml
subscribe_email:
# RSS feeds can list your email address if you like
email:

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# If publishing to a subdirectory as in http://site.com/project set 'root: /project'
root: /
permalink: /blog/:year/:month/:day/:title/
source: source
destination: public
plugins: plugins
code_dir: downloads/code
category_dir: blog/categories
markdown: rdiscount
rdiscount:
  extensions:
    - autolink
    - footnotes
    - smart
pygments: false # default python pygments have been replaced by pygments.rb

paginate: 10          # Posts per page on the blog index
pagination_dir: blog  # Directory base for pagination URLs eg. /blog/page/2/
recent_posts: 5       # Posts in the sidebar Recent Posts section
excerpt_link: "Read on &rarr;"  # "Continue reading" link text at the bottom of excerpted articles

titlecase: true       # Converts page and post titles to titlecase

# list each of the sidebar modules you want to include, in the order you want them to appear.
# To add custom asides, create files in /source/_includes/custom/asides/ and add them to the list like 'custom/asides/custom_aside_name.html'
#default_asides: [asides/recent_posts.html, asides/github.html, asides/delicious.html, asides/pinboard.html, asides/googleplus.html]
default_asides:
  - custom/asides/categories.html
  - asides/recent_posts.html

# Each layout uses the default asides, but they can have their own asides instead. Simply uncomment the lines below
# and add an array with the asides you want to use.
blog_index_asides:
  - custom/asides/categories.html
  - asides/recent_posts.html
post_asides:
  - custom/asides/categories.html
  - asides/recent_posts.html
# page_asides:

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

# Github repositories
github_user:  dinhyen
github_repo_count: 0
github_show_profile_link: true
github_skip_forks: true

# Twitter
twitter_user: dinhyen
twitter_tweet_button: true

# Google +1
google_plus_one: false
google_plus_one_size: medium

# Google Plus Profile
# Hidden: No visible button, just add author information to search results
googleplus_user:  dinhyen
googleplus_hidden: false

# Pinboard
pinboard_user:
pinboard_count: 3

# Delicious
delicious_user:
delicious_count: 3

# Disqus Comments
disqus_short_name:
disqus_show_comment_count: false

# Google Analytics
google_analytics_tracking_id: UA-24469490-1

# Facebook Like
facebook_like: false

# ----------------------- #
#   Page Settings         #
# ----------------------- #
travel:
  austria:
    - name: "Hallstatt"
      url:  hallstatt
    - name: Innsbruck
      url:  innsbruck
    - name: "Melk"
      url:  melk
    - name: Mondsee
      url:  mondsee
    - name: Salzburg
      url:  salzburg
    - name: Vienna
      url:  vienna
  canada:
    - name: Calgary
      url:  calgary
    - name: "Canmore"
      url:  canmore
    - name: "Halifax"
      url:  halifax
    - name: "Kelowna"
      url:  kelowna
    - name: "Keremeos"
      url:  keremeos
    - name: "Qu&eacute;bec"
      url:  2011/07/05/quebec-1-july
  costa-rica:
    - name: Volcan Arenal
      url:  2011/05/30/costa-rica-day-3-thursday-arenal
    - name: Caño Negro National Wildlife Refuge
      url:  2011/05/30/costa-rica-day-4-friday-arenal-to-monteverde
    - name: Monteverde 1
      url:  2011/05/30/costa-rica-day-5-saturday-monteverde
    - name: Monteverde 2
      url:  2011/05/30/costa-rica-day-6-sunday-monteverde-to-san-jose
    - name: "Volcan Po&aacute;s"
      url:  2011/05/29/costa-rica-day-2-wednesday-san-jose-to-arenal
    - name: San Jose
      url:  2011/05/30/costa-rica-day-7-monday-san-jose
  czech-republic:
    - name: "Český Krumlov"
      url:  cesky-krumlov
    - name: "Prague"
      url:  prague      
  france:
    - name: Aix-en-Provence
      url:  aix-en-provence
    - name: Arromanches-les-Bains
      url:  arromanches-les-bains
    - name: Avignon
      url:  avignon
    - name: Bayeux
      url:  bayeux
    - name: Bonnieux
      url:  bonnieux
    - name: Cannes
      url:  cannes
    - name: "Chateau de Vasc&oelig;uil"
      url:  chateau-de-vascoeuil
    - name: Colleville-sur-Mer
      url:  colleville-sur-mer
    - name: Colmar
      url:  colmar
    - name: Connelles
      url:  connelles
    - name: "&Eacute;tretat"
      url:  etretat
    - name: "&Egrave;ze"
      url:  eze
    - name: "F&eacute;camp"
      url:  fecamp
    - name: "Fontaine-de-Vaucluse"
      url:  fontaine-de-vaucluse
    - name: "Fontainebleau"
      url:  fontainebleau
    - name: "Giverny"
      url:  giverny
    - name: "Gordes"
      url:  gordes
    - name: Gorges du Verdon
      url:  gorges-du-verdon
    - name: "Honfleur"
      url:  honfleur
    - name: "Les Andelys"
      url:  les-andelys
    - name: "Lisieux"
      url:  lisieux
    - name: "Lyons-la-For&ecirc;t"
      url:  lyons-la-foret
    - name: "Marseille"
      url:  marseille
    - name: "Menton"
      url:  menton
    - name: "Mont St-Michel"
      url:  mont-st-michel
    - name: "Nice"
      url:  nice
    - name: "N&icirc;mes"
      url:  nimes
    - name: "Paris"
      url:  paris
    - name: "Peille"
      url:  peille
    - name: "Pont-Audemer"
      url:  pont-audemer
    - name: "Pont-de-l'Arche"
      url:  pont-de-l-arche
    - name: "Reims"
      url:  reims
    - name: "Rouen"
      url:  rouen
    - name: "Roussillon"
      url:  roussillon
    - name: "Saorge"
      url:  saorge
    - name: "St-Samson-de-la-Roque"
      url:  st-samson-de-la-roque
    - name: "Strasbourg"
      url:  strasbourg
    - name: "Trigance"
      url:  trigance
    - name: "Trouville-sur-Mer"
      url:  trouville
    - name: "Vernon"
      url:  vernon
  germany:
    - name: "Munich"
      url:  munich
    - name: "Rothenburg ob der Tauber"
      url:  rothenburg-ob-der-tauber
    - name: "Schloss Neuschwanstein"
      url:  schloss-neuschwanstein
  monaco:
    - name: "Monaco"
      url: monaco
  netherlands:
    - name: Amsterdam
      url:  amsterdam
    - name: Arnhem
      url:  arnhem
    - name: Boxmeer
      url:  boxmeer
    - name: Delft
      url:  delft
    - name: Nijmegen
      url:  nijmegen
    - name: Roosendaal
      url:  roosendaal
    - name: The Hague
      url:  the-hague
    - name: Urk
      url:  urk
    - name: Utrecht
      url:  utrecht
  peru:
    - name: Cusco
      url:  2012/07/17/cusco
    - name: Lima
      url:  2012/07/16/lima
    - name: Machu Picchu
      url:  2012/07/31/machu-picchu
    - name: Ollantaytambo
      url:  2012/08/07/ollantaytambo
    - name: Pisac
      url:  2012/07/19/pisac
    - name: Sacsayhuaman
      url:  2012/07/24/sacsayhuaman
  uk:
    - name: "London"
      url:  london
  usa:
    - name: "Arizona"
      url:  arizona
      places:
        - name: "Grand Canyon National Park"
          url:  grand-canyon-national-park
    - name: "Florida"
      url:  florida
      places:
        - name: "Cape Canaveral"
          url:  cape-canaveral
    - name: "Hawaii"
      url:  hawaii
      places:
        - name: "Hawaii Island"
          url:  hawaii
    - name: "Massachusetts"
      url:  massachusetts
      places:
        - name: "Boston"
          url:  boston
        - name: Waterfalls of Massachusetts
          url:  waterfalls
    - name: "Maine"
      url:  maine
      places:
        - name: "Acadia National Park"
          url:  acadia-national-park
    - name: "Montana"
      url:  montana
      places:
        - name: "Glacier National Park"
          url:  glacier-national-park
    - name: "Nevada"
      url:  nevada
      places:
        - name: "Death Valley National Park"
          url:  death-valley-national-park
    - name: "Oregon"
      url:  oregon
      places:
        - name: "Astoria"
          url:  astoria
        - name: "Cannon Beach"
          url:  cannon-beach
        - name: "Crater Lake National Park"
          url:  crater-lake-national-park
    - name: "Utah"
      url:  utah
      places:
        - name: "Bryce Canyon National Park"
          url:  bryce-canyon-national-park
    - name: "Virginia"
      url:  virginia
      places:
        - name: "Great Falls"
          url:  great-falls